### PR TITLE
Added slider for water and light 

### PR DESCRIPTION
**Pull request by Sushilkc855**

### CODE REVIEW

**Comment by hannesmann** [comment]
* Icons should be changed to something that we're allowed to use
* Fix dark mode
* Checkbox should say "advanced info" instead of "advance info"
* Checkbox should be a switch instead (https://m3.material.io/components/switch/overview)
* Remove water and light level text under title 
* Water level should say "Moisture" or "Moisture level"
* Advanced info should change "low medium high" to something else like "50 100 150"

**Comment by hannesmann** [comment]
Maybe: Make notification bar match color of background

**Review by gyuudon3187 — COMMENTED** [review]
reviewed

**Review by gyuudon3187 — APPROVED** [review]
reviewed

**Pull request merged**
